### ISSUE TITLE
[Request] Disable Upgrades 2 and 3

### ISSUE THREAD

**Issue by pakoito** [web-lux/starforged-asset-workbench#4]
I would like to be able to build a card with a single upgrade level.

**Comment by web-lux** [comment]
Thanks for the feedback ! I'm thinking of doing a V2 for the workbench so I'll add both of your suggestions to the list of features to add. I'll close the issues once it's done.

**Comment by web-lux** [comment]
Sorry for the long wait, I was very busy with life and work. Implemented as of today 👍
